# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
    - "v*"
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # TODO make use of build spec and do it
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
          repository: vijaysamanuri/leeroy-app
          tag_with_ref: true
        env:
          image_tag: ${GITHUB_REF##*/}
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/vijaysamanuri/leeroy-app:${{ image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
        env:
          image_tag: ${GITHUB_REF##*/}
      - name: Checkout config repo
        uses: actions/checkout@v2.3.3
        with:
          repository: vijaysamanuri/leeroy-app-config
          ref: dev
          path: leeroy-app-config
          persist-credentials: false
          token: ${{ secrets.PAT_FOR_PUSH }}     
      - name: update imageTag
        run: |
          echo "tag is ${GITHUB_REF##*/}"
          tag="${GITHUB_REF##*/}"
          ls ${GITHUB_WORKSPACE}
          echo "Copying leeroy-app's only deploy spec developer written hspec to leeroy-app-config config repo..."
          #cp ${GITHUB_WORKSPACE}/leeroy-app.hspec.yaml ${GITHUB_WORKSPACE}/leeroy-app-config/leeroy-app.hspec.yaml
          echo "Updating Image Tag ${tag} in config repo [leeroy-config-repo]..."
          sed -i "s/tag:.*/tag: ${tag}/g" ${GITHUB_WORKSPACE}/leeroy-app-config/leeroy-app.hspec.yaml
          cd ${GITHUB_WORKSPACE}/leeroy-app-config
          git config --global user.email "vijay.samanuri@hyscale.io"
          git config --global user.name "vijaysamanuri"
          git add .
          git commit -m "Update tag ${tag}"
          git log -3
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.0
        with:
          path: leeroy-app-config
          committer: vijay rama raju samanuri <vijay.samanuri@hyscale.io>
          author: vijay rama raju samanuri <vijay.samanuri@hyscale.io>
          token: ${{ secrets.PAT_FOR_PUSH }}
          
       #todo:
          
        
 

 
          
      

      
  
